services:
- type: web
  name: predict-tavi
  runtime: python
  repo: https://github.com/harrisonnguyen/tavi
  plan: starter
  envVars:
  - key: PYTHON_VERSION
    value: 3.13.0
  region: singapore
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:server
version: "1"
